//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int ItemID { get; set; }
        public int RestaurantID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string ItemImage { get; set; }
        public string Price { get; set; }
        public Nullable<int> Required { get; set; }
        public Nullable<int> Additional { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual ItemCategoty ItemCategoty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
