//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int RestaurantID { get; set; }
        public string R_Name { get; set; }
        public string R_Image { get; set; }
        public string R_Tags { get; set; }
        public Nullable<double> R_Rating { get; set; }
        public string R_OpenTime { get; set; }
        public string R_DeliveryTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
