//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int AUTOID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public string ItemNote { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
